# coding: utf-8

"""
    Hotel Booking API

    This API represents relation between Hotel and Room entities

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotel_booking_sdk.models.hotel import Hotel

class TestHotel(unittest.TestCase):
    """Hotel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Hotel:
        """Test Hotel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Hotel`
        """
        model = Hotel()
        if include_optional:
            return Hotel(
                id = '123',
                name = 'Grand Plaza',
                address = '123 Main St, Kyiv',
                rating = 4.5,
                created_at = '2025-04-01T12:00Z'
            )
        else:
            return Hotel(
        )
        """

    def testHotel(self):
        """Test Hotel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
