# coding: utf-8

"""
    Hotel Booking API

    This API represents relation between Hotel and Room entities

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotel_booking_sdk.models.room_update import RoomUpdate

class TestRoomUpdate(unittest.TestCase):
    """RoomUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoomUpdate:
        """Test RoomUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoomUpdate`
        """
        model = RoomUpdate()
        if include_optional:
            return RoomUpdate(
                number = '',
                type = '',
                price = 1.337,
                status = 'available'
            )
        else:
            return RoomUpdate(
        )
        """

    def testRoomUpdate(self):
        """Test RoomUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
