# coding: utf-8

"""
    Hotel Booking API

    This API represents relation between Hotel and Room entities

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotel_booking_sdk.models.room import Room

class TestRoom(unittest.TestCase):
    """Room unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Room:
        """Test Room
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Room`
        """
        model = Room()
        if include_optional:
            return Room(
                id = '456',
                hotel_id = '123',
                number = '101',
                type = 'double',
                price = 120.0,
                status = 'available'
            )
        else:
            return Room(
        )
        """

    def testRoom(self):
        """Test Room"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
