# coding: utf-8

# flake8: noqa
"""
    Hotel Booking API

    This API represents relation between Hotel and Room entities

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from hotel_booking_sdk.models.hotel import Hotel
from hotel_booking_sdk.models.hotel_create import HotelCreate
from hotel_booking_sdk.models.hotel_update import HotelUpdate
from hotel_booking_sdk.models.room import Room
from hotel_booking_sdk.models.room_create import RoomCreate
from hotel_booking_sdk.models.room_update import RoomUpdate
