# coding: utf-8

# flake8: noqa

"""
    Hotel Booking API

    This API represents relation between Hotel and Room entities

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from hotel_booking_sdk.api.default_api import DefaultApi

# import ApiClient
from hotel_booking_sdk.api_response import ApiResponse
from hotel_booking_sdk.api_client import ApiClient
from hotel_booking_sdk.configuration import Configuration
from hotel_booking_sdk.exceptions import OpenApiException
from hotel_booking_sdk.exceptions import ApiTypeError
from hotel_booking_sdk.exceptions import ApiValueError
from hotel_booking_sdk.exceptions import ApiKeyError
from hotel_booking_sdk.exceptions import ApiAttributeError
from hotel_booking_sdk.exceptions import ApiException

# import models into sdk package
from hotel_booking_sdk.models.hotel import Hotel
from hotel_booking_sdk.models.hotel_create import HotelCreate
from hotel_booking_sdk.models.hotel_update import HotelUpdate
from hotel_booking_sdk.models.room import Room
from hotel_booking_sdk.models.room_create import RoomCreate
from hotel_booking_sdk.models.room_update import RoomUpdate
